version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - revive
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    exhaustruct:
      exclude:
        - GetPayloadsFilters
        - cobra.Command
        - database.*Entry
        - http.Server
        - logrus.*Formatter
        - Options
        - Datastore
        - Housekeeper
        - MockBeaconClient
        - RelayAPI
        - Webserver
    gosec:
      excludes:
        - G108
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
