services:
  mev_rpc:
    env_file: ".env"
    container_name: mev_rpc
    image: mev-rpc:alpha
    environment:
      RPC_ENDPOINT: ${RPC_ENDPOINT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    ports:
      - "8080:8080"
      - "8090:8090"
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl localhost:8080/readyz"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    env_file: ".env"
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: mev_analytics 
    volumes:
      - db:/data/postgres
    ports:
      - "5532:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db:
